import mongoose from 'mongoose';
import dotenv from 'dotenv';

dotenv.config({ path: '.env.local' });

const ProductSchema = new mongoose.Schema({
    name: { type: String, required: true },
    slug: { type: String, unique: true },
    description: { type: String, required: true },
    price: { type: Number, required: true },
    images: [String],
    category: { type: String, required: true },
    stock: { type: Number, default: 100 },
    sku: String,
    purity: String,
    content: String,
    size: String,
    form: String,
    soldout_status: { type: Boolean, default: false },
    featured: { type: Boolean, default: false },
}, { timestamps: true });

const Product = mongoose.models.Product || mongoose.model('Product', ProductSchema);

const products = [
    {
        name: "Semaglutide 5mg",
        slug: "semaglutide-5mg",
        description: "Semaglutide is a GLP-1 receptor agonist that regulates appetite, reduces caloric intake, and improves glycemic control. Commonly researched for weight management, obesity treatment, and type 2 diabetes support. Administered via subcutaneous injection.",
        price: 40,
        images: ["/images/peptide-injections.webp"],
        category: "Peptides / Weight Management",
        stock: 0,
        sku: "SM5",
        purity: "≥99.0%",
        content: "5mg",
        size: "5mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Semaglutide 10mg",
        slug: "semaglutide-10mg",
        description: "Semaglutide is a GLP-1 receptor agonist that regulates appetite, reduces caloric intake, and improves glycemic control. Commonly researched for weight management, obesity treatment, and type 2 diabetes support. Administered via subcutaneous injection.",
        price: 48,
        images: ["/images/peptide-injections.webp"],
        category: "Peptides / Weight Management",
        stock: 0,
        sku: "SM10",
        purity: "≥99.0%",
        content: "10mg",
        size: "10mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Semaglutide 15mg",
        slug: "semaglutide-15mg",
        description: "Semaglutide is a GLP-1 receptor agonist that regulates appetite, reduces caloric intake, and improves glycemic control. Commonly researched for weight management, obesity treatment, and type 2 diabetes support. Administered via subcutaneous injection.",
        price: 58,
        images: ["/images/peptide-injections.webp"],
        category: "Peptides / Weight Management",
        stock: 0,
        sku: "SM15",
        purity: "≥99.0%",
        content: "15mg",
        size: "15mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Semaglutide 20mg",
        slug: "semaglutide-20mg",
        description: "Semaglutide is a GLP-1 receptor agonist that regulates appetite, reduces caloric intake, and improves glycemic control. Commonly researched for weight management, obesity treatment, and type 2 diabetes support. Administered via subcutaneous injection.",
        price: 73,
        images: ["/images/peptide-injections.webp"],
        category: "Peptides / Weight Management",
        stock: 0,
        sku: "SM20",
        purity: "≥99.0%",
        content: "20mg",
        size: "20mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Semaglutide 30mg",
        slug: "semaglutide-30mg",
        description: "Semaglutide is a GLP-1 receptor agonist that regulates appetite, reduces caloric intake, and improves glycemic control. Commonly researched for weight management, obesity treatment, and type 2 diabetes support. Administered via subcutaneous injection.",
        price: 90,
        images: ["/images/peptide-injections.webp"],
        category: "Peptides / Weight Management",
        stock: 0,
        sku: "SM30",
        purity: "≥99.0%",
        content: "30mg",
        size: "30mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Tirzepatide 5mg",
        slug: "tirzepatide-5mg",
        description: "Tirzepatide is a novel dual GIP and GLP-1 receptor agonist. This dual mechanism provides enhanced glucose regulation and significant weight loss outcomes. Research indicates superior efficacy compared to single-receptor agonists for metabolic syndrome and obesity.",
        price: 45,
        images: ["/images/peptide-injections.webp"],
        category: "Peptides / Weight Management",
        stock: 0,
        sku: "TR5",
        purity: "≥99.0%",
        content: "5mg",
        size: "5mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Tirzepatide 10mg",
        slug: "tirzepatide-10mg",
        description: "Tirzepatide is a novel dual GIP and GLP-1 receptor agonist. This dual mechanism provides enhanced glucose regulation and significant weight loss outcomes. Research indicates superior efficacy compared to single-receptor agonists for metabolic syndrome and obesity.",
        price: 58,
        images: ["/images/peptide-injections.webp"],
        category: "Peptides / Weight Management",
        stock: 0,
        sku: "TR10",
        purity: "≥99.0%",
        content: "10mg",
        size: "10mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Tirzepatide 15mg",
        slug: "tirzepatide-15mg",
        description: "Tirzepatide is a novel dual GIP and GLP-1 receptor agonist. This dual mechanism provides enhanced glucose regulation and significant weight loss outcomes. Research indicates superior efficacy compared to single-receptor agonists for metabolic syndrome and obesity.",
        price: 70,
        images: ["/images/peptide-injections.webp"],
        category: "Peptides / Weight Management",
        stock: 0,
        sku: "TR15",
        purity: "≥99.0%",
        content: "15mg",
        size: "15mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Tirzepatide 20mg",
        slug: "tirzepatide-20mg",
        description: "Tirzepatide is a novel dual GIP and GLP-1 receptor agonist. This dual mechanism provides enhanced glucose regulation and significant weight loss outcomes. Research indicates superior efficacy compared to single-receptor agonists for metabolic syndrome and obesity.",
        price: 88,
        images: ["/images/peptide-injections.webp"],
        category: "Peptides / Weight Management",
        stock: 0,
        sku: "TR20",
        purity: "≥99.0%",
        content: "20mg",
        size: "20mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Tirzepatide 30mg",
        slug: "tirzepatide-30mg",
        description: "Tirzepatide is a novel dual GIP and GLP-1 receptor agonist. This dual mechanism provides enhanced glucose regulation and significant weight loss outcomes. Research indicates superior efficacy compared to single-receptor agonists for metabolic syndrome and obesity.",
        price: 100,
        images: ["/images/peptide-injections.webp"],
        category: "Peptides / Weight Management",
        stock: 0,
        sku: "TR30",
        purity: "≥99.0%",
        content: "30mg",
        size: "30mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Tirzepatide 40mg",
        slug: "tirzepatide-40mg",
        description: "Tirzepatide is a novel dual GIP and GLP-1 receptor agonist. This dual mechanism provides enhanced glucose regulation and significant weight loss outcomes. Research indicates superior efficacy compared to single-receptor agonists for metabolic syndrome and obesity.",
        price: 120,
        images: ["/images/peptide-injections.webp"],
        category: "Peptides / Weight Management",
        stock: 0,
        sku: "TR40",
        purity: "≥99.0%",
        content: "40mg",
        size: "40mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Tirzepatide 50mg",
        slug: "tirzepatide-50mg",
        description: "Tirzepatide is a novel dual GIP and GLP-1 receptor agonist. This dual mechanism provides enhanced glucose regulation and significant weight loss outcomes. Research indicates superior efficacy compared to single-receptor agonists for metabolic syndrome and obesity.",
        price: 155,
        images: ["/images/peptide-injections.webp"],
        category: "Peptides / Weight Management",
        stock: 0,
        sku: "TR50",
        purity: "≥99.0%",
        content: "50mg",
        size: "50mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Tirzepatide 60mg",
        slug: "tirzepatide-60mg",
        description: "Tirzepatide is a novel dual GIP and GLP-1 receptor agonist. This dual mechanism provides enhanced glucose regulation and significant weight loss outcomes. Research indicates superior efficacy compared to single-receptor agonists for metabolic syndrome and obesity.",
        price: 180,
        images: ["/images/peptide-injections.webp"],
        category: "Peptides / Weight Management",
        stock: 0,
        sku: "TR60",
        purity: "≥99.0%",
        content: "60mg",
        size: "60mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Retatrutide 5mg",
        slug: "retatrutide-5mg",
        description: "Retatrutide is a triple hormone receptor agonist targeting GLP-1, GIP, and glucagon receptors. This innovative mechanism offers unprecedented metabolic benefits including substantial weight loss, improved insulin sensitivity, and favorable body composition changes.",
        price: 50,
        images: ["/images/peptide-injections.webp"],
        category: "Peptides / Weight Management",
        stock: 0,
        sku: "RT5",
        purity: "≥99.0%",
        content: "5mg",
        size: "5mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Retatrutide 10mg",
        slug: "retatrutide-10mg",
        description: "Retatrutide is a triple hormone receptor agonist targeting GLP-1, GIP, and glucagon receptors. This innovative mechanism offers unprecedented metabolic benefits including substantial weight loss, improved insulin sensitivity, and favorable body composition changes.",
        price: 75,
        images: ["/images/peptide-injections.webp"],
        category: "Peptides / Weight Management",
        stock: 0,
        sku: "RT10",
        purity: "≥99.0%",
        content: "10mg",
        size: "10mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Retatrutide 15mg",
        slug: "retatrutide-15mg",
        description: "Retatrutide is a triple hormone receptor agonist targeting GLP-1, GIP, and glucagon receptors. This innovative mechanism offers unprecedented metabolic benefits including substantial weight loss, improved insulin sensitivity, and favorable body composition changes.",
        price: 95,
        images: ["/images/peptide-injections.webp"],
        category: "Peptides / Weight Management",
        stock: 0,
        sku: "RT15",
        purity: "≥99.0%",
        content: "15mg",
        size: "15mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Retatrutide 20mg",
        slug: "retatrutide-20mg",
        description: "Retatrutide is a triple hormone receptor agonist targeting GLP-1, GIP, and glucagon receptors. This innovative mechanism offers unprecedented metabolic benefits including substantial weight loss, improved insulin sensitivity, and favorable body composition changes.",
        price: 115,
        images: ["/images/peptide-injections.webp"],
        category: "Peptides / Weight Management",
        stock: 0,
        sku: "RT20",
        purity: "≥99.0%",
        content: "20mg",
        size: "20mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "HGH 10IU",
        slug: "hgh-10iu",
        description: "Human Growth Hormone (HGH) is a 191-amino acid peptide hormone essential for growth, cell reproduction, and regeneration. Widely researched for anti-aging protocols, muscle development, injury recovery, and metabolic optimization. Supports lean muscle growth and fat metabolism.",
        price: 58,
        images: ["/images/peptide-injections.webp"],
        category: "Growth Hormones",
        stock: 0,
        sku: "H10",
        purity: "≥99.0%",
        content: "10IU",
        size: "10IU × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "HGH 15IU",
        slug: "hgh-15iu",
        description: "Human Growth Hormone (HGH) is a 191-amino acid peptide hormone essential for growth, cell reproduction, and regeneration. Widely researched for anti-aging protocols, muscle development, injury recovery, and metabolic optimization. Supports lean muscle growth and fat metabolism.",
        price: 85,
        images: ["/images/peptide-injections.webp"],
        category: "Growth Hormones",
        stock: 0,
        sku: "H15",
        purity: "≥99.0%",
        content: "15IU",
        size: "15IU × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "HGH 24IU",
        slug: "hgh-24iu",
        description: "Human Growth Hormone (HGH) is a 191-amino acid peptide hormone essential for growth, cell reproduction, and regeneration. Widely researched for anti-aging protocols, muscle development, injury recovery, and metabolic optimization. Supports lean muscle growth and fat metabolism.",
        price: 130,
        images: ["/images/peptide-injections.webp"],
        category: "Growth Hormones",
        stock: 0,
        sku: "H24",
        purity: "≥99.0%",
        content: "24IU",
        size: "24IU × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Melatonin 10mg",
        slug: "melatonin-10mg",
        description: "Melatonin is a hormone primarily secreted by the pineal gland that regulates sleep-wake cycles and circadian rhythms. Researched for sleep disorders, jet lag, and as a potent antioxidant. Supports optimal recovery, immune function, and cellular health.",
        price: 60,
        images: ["/images/peptide-injections.webp"],
        category: "Wellness & Recovery",
        stock: 0,
        sku: "MT10",
        purity: "≥99.0%",
        content: "10mg",
        size: "10mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Melanotan II 10mg",
        slug: "melanotan-ii-10mg",
        description: "Melanotan II is a synthetic analog of α-MSH (alpha-melanocyte-stimulating hormone) that induces melanogenesis and tanning response. Researched for skin pigmentation, aphrodisiac effects, and appetite suppression. Provides natural-looking tan with minimal sun exposure.",
        price: 55,
        images: ["/images/peptide-injections.webp"],
        category: "Cosmetic Peptides",
        stock: 0,
        sku: "ML10",
        purity: "≥99.0%",
        content: "10mg",
        size: "10mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "GHK-Cu 50mg",
        slug: "ghk-cu-50mg",
        description: "GHK-Cu is a naturally occurring copper-binding peptide complex that promotes wound healing, skin repair, and hair growth. Research demonstrates powerful anti-aging properties, collagen synthesis stimulation, and antioxidant effects. Widely used in skincare and regenerative medicine.",
        price: 40,
        images: ["/images/peptide-injections.webp"],
        category: "Cosmetic Peptides",
        stock: 0,
        sku: "CU50",
        purity: "≥99.0%",
        content: "50mg",
        size: "50mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "GHK-Cu 100mg",
        slug: "ghk-cu-100mg",
        description: "GHK-Cu is a naturally occurring copper-binding peptide complex that promotes wound healing, skin repair, and hair growth. Research demonstrates powerful anti-aging properties, collagen synthesis stimulation, and antioxidant effects. Widely used in skincare and regenerative medicine.",
        price: 55,
        images: ["/images/peptide-injections.webp"],
        category: "Cosmetic Peptides",
        stock: 0,
        sku: "CU100",
        purity: "≥99.0%",
        content: "100mg",
        size: "100mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Glutathione 1500mg",
        slug: "glutathione",
        description: "Glutathione is the body's master antioxidant, essential for detoxification, immune function, and cellular protection. Research indicates benefits for skin brightening, liver support, and oxidative stress reduction. Supports overall health and longevity.",
        price: 80,
        images: ["/images/peptide-injections.webp"],
        category: "Wellness & Recovery",
        stock: 0,
        sku: "GTT",
        purity: "≥99.0%",
        content: "1500mg",
        size: "1500mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Cagrilintide 5mg",
        slug: "cagrilintide-5mg",
        description: "Cagrilintide is an amylin analog that works synergistically with GLP-1 receptor agonists. Research shows enhanced appetite regulation, prolonged satiety, and improved weight loss outcomes when combined with semaglutide or other GLP-1 peptides.",
        price: 130,
        images: ["/images/peptide-injections.webp"],
        category: "Peptides / Weight Management",
        stock: 0,
        sku: "CGL5",
        purity: "≥99.0%",
        content: "5mg",
        size: "5mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Cagrilintide 10mg",
        slug: "cagrilintide-10mg",
        description: "Cagrilintide is an amylin analog that works synergistically with GLP-1 receptor agonists. Research shows enhanced appetite regulation, prolonged satiety, and improved weight loss outcomes when combined with semaglutide or other GLP-1 peptides.",
        price: 215,
        images: ["/images/peptide-injections.webp"],
        category: "Peptides / Weight Management",
        stock: 0,
        sku: "CGL10",
        purity: "≥99.0%",
        content: "10mg",
        size: "10mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Snap-8 10mg",
        slug: "snap-8",
        description: "Snap-8 is an eight-amino acid peptide that reduces expression wrinkles by inhibiting the SNARE complex formation. Research demonstrates significant reduction in wrinkle depth and prevention of new wrinkle formation. Ideal for topical and injectable anti-aging protocols.",
        price: 50,
        images: ["/images/peptide-injections.webp"],
        category: "Cosmetic Peptides",
        stock: 0,
        sku: "NP810",
        purity: "≥99.0%",
        content: "10mg",
        size: "10mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Semax 5mg",
        slug: "semax-5mg",
        description: "Semax is an ACTH (4-10) analog with no hormonal activity but potent nootropic effects. Research demonstrates enhanced cognitive function, neuroprotection, attention improvement, and BDNF upregulation. Widely used for focus, memory enhancement, and stroke recovery.",
        price: 50,
        images: ["/images/peptide-injections.webp"],
        category: "Nootropics",
        stock: 0,
        sku: "XA5",
        purity: "≥99.0%",
        content: "5mg",
        size: "5mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Semax 10mg",
        slug: "semax-10mg",
        description: "Semax is an ACTH (4-10) analog with no hormonal activity but potent nootropic effects. Research demonstrates enhanced cognitive function, neuroprotection, attention improvement, and BDNF upregulation. Widely used for focus, memory enhancement, and stroke recovery.",
        price: 65,
        images: ["/images/peptide-injections.webp"],
        category: "Nootropics",
        stock: 0,
        sku: "XA10",
        purity: "≥99.0%",
        content: "10mg",
        size: "10mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Selank 5mg",
        slug: "selank-5mg",
        description: "Selank is a synthetic analog of tuftsin with anxiolytic and nootropic properties. Research shows reduction in anxiety, improved mood, enhanced cognitive function, and stress resilience. Does not cause sedation or dependence unlike traditional anxiolytics.",
        price: 55,
        images: ["/images/peptide-injections.webp"],
        category: "Nootropics",
        stock: 0,
        sku: "SK5",
        purity: "≥99.0%",
        content: "5mg",
        size: "5mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Selank 10mg",
        slug: "selank-10mg",
        description: "Selank is a synthetic analog of tuftsin with anxiolytic and nootropic properties. Research shows reduction in anxiety, improved mood, enhanced cognitive function, and stress resilience. Does not cause sedation or dependence unlike traditional anxiolytics.",
        price: 60,
        images: ["/images/peptide-injections.webp"],
        category: "Nootropics",
        stock: 0,
        sku: "SK10",
        purity: "≥99.0%",
        content: "10mg",
        size: "10mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "IGF-1 LR3 0.1mg",
        slug: "igf-1-lr3-01mg",
        description: "IGF-1 LR3 (Long R3) is a recombinant analog of IGF-1 with extended half-life and enhanced anabolic activity. Research indicates potent muscle growth, tissue repair, and fat loss effects. One of the most powerful growth factors available for athletic performance.",
        price: 50,
        images: ["/images/peptide-injections.webp"],
        category: "Growth Factors",
        stock: 0,
        sku: "IG01",
        purity: "≥99.0%",
        content: "0.1mg",
        size: "0.1mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "IGF-1 LR3 1mg",
        slug: "igf-1-lr3-1mg",
        description: "IGF-1 LR3 (Long R3) is a recombinant analog of IGF-1 with extended half-life and enhanced anabolic activity. Research indicates potent muscle growth, tissue repair, and fat loss effects. One of the most powerful growth factors available for athletic performance.",
        price: 225,
        images: ["/images/peptide-injections.webp"],
        category: "Growth Factors",
        stock: 0,
        sku: "IG1",
        purity: "≥99.0%",
        content: "1mg",
        size: "1mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Tesamorelin 5mg",
        slug: "tesamorelin-5mg",
        description: "Tesamorelin is a synthetic GHRH analog that stimulates growth hormone secretion from the pituitary gland. Research demonstrates particular effectiveness for reducing visceral fat, improving lipid profiles, and enhancing cognitive function. FDA-approved for HIV-associated lipodystrophy.",
        price: 120,
        images: ["/images/peptide-injections.webp"],
        category: "Growth Hormones",
        stock: 0,
        sku: "TSM5",
        purity: "≥99.0%",
        content: "5mg",
        size: "5mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Tesamorelin 10mg",
        slug: "tesamorelin-10mg",
        description: "Tesamorelin is a synthetic GHRH analog that stimulates growth hormone secretion from the pituitary gland. Research demonstrates particular effectiveness for reducing visceral fat, improving lipid profiles, and enhancing cognitive function. FDA-approved for HIV-associated lipodystrophy.",
        price: 205,
        images: ["/images/peptide-injections.webp"],
        category: "Growth Hormones",
        stock: 0,
        sku: "TSM10",
        purity: "≥99.0%",
        content: "10mg",
        size: "10mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Tesamorelin 15mg",
        slug: "tesamorelin-15mg",
        description: "Tesamorelin is a synthetic GHRH analog that stimulates growth hormone secretion from the pituitary gland. Research demonstrates particular effectiveness for reducing visceral fat, improving lipid profiles, and enhancing cognitive function. FDA-approved for HIV-associated lipodystrophy.",
        price: 225,
        images: ["/images/peptide-injections.webp"],
        category: "Growth Hormones",
        stock: 0,
        sku: "TSM15",
        purity: "≥99.0%",
        content: "15mg",
        size: "15mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Ipamorelin 5mg",
        slug: "ipamorelin-5mg",
        description: "Ipamorelin is a selective growth hormone secretagogue (GHS) with minimal side effects. Stimulates GH release through ghrelin receptor activation while avoiding significant cortisol or prolactin elevation. Highly regarded for its safety profile and effectiveness.",
        price: 50,
        images: ["/images/peptide-injections.webp"],
        category: "Growth Hormones",
        stock: 0,
        sku: "IP5",
        purity: "≥99.0%",
        content: "5mg",
        size: "5mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Ipamorelin 10mg",
        slug: "ipamorelin-10mg",
        description: "Ipamorelin is a selective growth hormone secretagogue (GHS) with minimal side effects. Stimulates GH release through ghrelin receptor activation while avoiding significant cortisol or prolactin elevation. Highly regarded for its safety profile and effectiveness.",
        price: 80,
        images: ["/images/peptide-injections.webp"],
        category: "Growth Hormones",
        stock: 0,
        sku: "IP10",
        purity: "≥99.0%",
        content: "10mg",
        size: "10mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "MOTS-c 10mg",
        slug: "mots-c-10mg",
        description: "MOTS-c is a mitochondrial-derived peptide that regulates metabolic homeostasis and insulin sensitivity. Research shows benefits for energy metabolism, exercise performance, obesity prevention, and age-related metabolic decline. Targets mitochondrial function directly.",
        price: 75,
        images: ["/images/peptide-injections.webp"],
        category: "Metabolic Peptides",
        stock: 0,
        sku: "MS10",
        purity: "≥99.0%",
        content: "10mg",
        size: "10mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "MOTS-c 40mg",
        slug: "mots-c-40mg",
        description: "MOTS-c is a mitochondrial-derived peptide that regulates metabolic homeostasis and insulin sensitivity. Research shows benefits for energy metabolism, exercise performance, obesity prevention, and age-related metabolic decline. Targets mitochondrial function directly.",
        price: 195,
        images: ["/images/peptide-injections.webp"],
        category: "Metabolic Peptides",
        stock: 0,
        sku: "MS40",
        purity: "≥99.0%",
        content: "40mg",
        size: "40mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Epithalon 10mg",
        slug: "epithalon-10mg",
        description: "Epithalon is a pineal gland peptide that regulates melatonin production and telomere length. Research indicates anti-aging effects, immune enhancement, and potential life extension properties. Supports circadian rhythm optimization and cellular rejuvenation.",
        price: 55,
        images: ["/images/peptide-injections.webp"],
        category: "Anti-Aging Peptides",
        stock: 0,
        sku: "ET10",
        purity: "≥99.0%",
        content: "10mg",
        size: "10mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "PT-141 10mg",
        slug: "pt-141-10mg",
        description: "PT-141 (Bremelanotide) activates melanocortin receptors MC1-MC5 with particular focus on MC4 for arousal enhancement. Research demonstrates benefits for sexual dysfunction, libido enhancement, and appetite suppression without vascular effects of PDE5 inhibitors.",
        price: 70,
        images: ["/images/peptide-injections.webp"],
        category: "Wellness & Recovery",
        stock: 0,
        sku: "P41",
        purity: "≥99.0%",
        content: "10mg",
        size: "10mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "DSIP 5mg",
        slug: "dsip-5mg",
        description: "DSIP is a neuropeptide that promotes deep delta-wave sleep and regulates circadian rhythms. Research indicates benefits for insomnia, stress adaptation, and pain management. Supports natural sleep architecture and recovery optimization.",
        price: 55,
        images: ["/images/peptide-injections.webp"],
        category: "Wellness & Recovery",
        stock: 0,
        sku: "DS5",
        purity: "≥99.0%",
        content: "5mg",
        size: "5mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Thymosin Alpha-1 5mg",
        slug: "thymosin-alpha-1-5mg",
        description: "Thymosin Alpha-1 is an immune-modulating peptide that enhances T-cell function and natural killer cell activity. Research shows benefits for immune deficiencies, viral infections, and as an adjunct to vaccines. Supports robust immune surveillance.",
        price: 95,
        images: ["/images/peptide-injections.webp"],
        category: "Immune Support",
        stock: 0,
        sku: "TA5",
        purity: "≥99.0%",
        content: "5mg",
        size: "5mg × 10 vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Bacteriostatic Water 3mL",
        slug: "bacteriostatic-water-3ml",
        description: "Bacteriostatic Water (BAC Water) is sterile water containing 0.9% benzyl alcohol for peptide and hormone reconstitution. The bacteriostatic agent prevents bacterial growth, allowing multiple withdrawals from the same vial. Essential for subcutaneous and intramuscular injections.",
        price: 8,
        images: ["/images/peptide-injections.webp"],
        category: "Supplies",
        stock: 0,
        sku: "WA3",
        purity: "Sterile Grade",
        content: "3mL",
        size: "3mL × 10 vials",
        form: "Liquid Solution",
    },
    {
        name: "Bacteriostatic Water 10mL",
        slug: "bacteriostatic-water-10ml",
        description: "Bacteriostatic Water (BAC Water) is sterile water containing 0.9% benzyl alcohol for peptide and hormone reconstitution. The bacteriostatic agent prevents bacterial growth, allowing multiple withdrawals from the same vial. Essential for subcutaneous and intramuscular injections.",
        price: 12,
        images: ["/images/peptide-injections.webp"],
        category: "Supplies",
        stock: 0,
        sku: "WA10",
        purity: "Sterile Grade",
        content: "10mL",
        size: "10mL × 10 vials",
        form: "Liquid Solution",
    },
];

async function seedProducts() {
    try {
        const mongoUri = process.env.MONGODB_URI;
        if (!mongoUri) {
            console.error('MONGODB_URI not found in .env.local');
            process.exit(1);
        }
        
        await mongoose.connect(mongoUri);
        console.log('Connected to MongoDB');

        await Product.deleteMany({});
        console.log('Deleted all existing products');

        for (const product of products) {
            await Product.create(product);
            console.log(`✓ ${product.name} (${product.sku})`);
        }

        console.log(`\n✓ Successfully added ${products.length} products`);

    } catch (error) {
        console.error('Error:', error);
    } finally {
        await mongoose.disconnect();
        console.log('Disconnected from MongoDB');
    }
}

seedProducts();
