import mongoose from 'mongoose';
import dotenv from 'dotenv';

dotenv.config({ path: '.env.local' });

const ProductSchema = new mongoose.Schema({
    name: { type: String, required: true },
    slug: { type: String, unique: true },
    description: { type: String, required: true },
    price: { type: Number, required: true },
    images: [String],
    category: { type: String, required: true },
    stock: { type: Number, default: 100 },
    sku: String,
    purity: String,
    content: String,
    size: String,
    form: String,
    soldout_status: { type: Boolean, default: false },
    featured: { type: Boolean, default: false },
}, { timestamps: true });

const Product = mongoose.models.Product || mongoose.model('Product', ProductSchema);

const products = [
    {
        name: "Tesamorelin",
        slug: "tesamorelin-10mg",
        description: "Tesamorelin is a synthetic analog of growth hormone-releasing hormone (GHRH). Used in research for fat loss, particularly visceral fat reduction, and metabolic improvements.",
        price: 205,
        images: ["/images/peptide-injections.webp"],
        category: "Weight Loss",
        stock: 100,
        sku: "TSM10",
        purity: "99%+",
        content: "10mg",
        size: "10mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Tesamorelin",
        slug: "tesamorelin-15mg",
        description: "Tesamorelin is a synthetic analog of growth hormone-releasing hormone (GHRH). Used in research for fat loss, particularly visceral fat reduction, and metabolic improvements.",
        price: 225,
        images: ["/images/peptide-injections.webp"],
        category: "Weight Loss",
        stock: 100,
        sku: "TSM15",
        purity: "99%+",
        content: "15mg",
        size: "15mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "VIP5",
        slug: "vip5",
        description: "VIP5 (Vasoactive Intestinal Peptide) is a neuropeptide involved in smooth muscle relaxation, vasodilation, and immune modulation. Research shows benefits for inflammatory conditions and cellular communication.",
        price: 85,
        images: ["/images/peptide-injections.webp"],
        category: "Performance",
        stock: 100,
        sku: "VP5",
        purity: "99%+",
        content: "5mg",
        size: "5mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "VIP10",
        slug: "vip10",
        description: "VIP10 (Vasoactive Intestinal Peptide) is a neuropeptide involved in smooth muscle relaxation, vasodilation, and immune modulation. Research shows benefits for inflammatory conditions and cellular communication.",
        price: 155,
        images: ["/images/peptide-injections.webp"],
        category: "Performance",
        stock: 100,
        sku: "VP10",
        purity: "99%+",
        content: "10mg",
        size: "10mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Ipamorelin",
        slug: "ipamorelin-5mg",
        description: "Ipamorelin is a selective growth hormone secretagogue (GHS) that stimulates GH release with minimal side effects. Highly potent and research-proven for growth hormone stimulation.",
        price: 50,
        images: ["/images/peptide-injections.webp"],
        category: "Performance",
        stock: 100,
        sku: "IP5",
        purity: "99%+",
        content: "5mg",
        size: "5mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Ipamorelin",
        slug: "ipamorelin-10mg",
        description: "Ipamorelin is a selective growth hormone secretagogue (GHS) that stimulates GH release with minimal side effects. Highly potent and research-proven for growth hormone stimulation.",
        price: 80,
        images: ["/images/peptide-injections.webp"],
        category: "Performance",
        stock: 100,
        sku: "IP10",
        purity: "99%+",
        content: "10mg",
        size: "10mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "MOTS-c",
        slug: "mots-c-10mg",
        description: "MOTS-C is a mitochondrial-derived peptide that influences metabolic regulation. Research shows benefits for energy, weight management, insulin sensitivity, and exercise performance.",
        price: 75,
        images: ["/images/peptide-injections.webp"],
        category: "Performance",
        stock: 100,
        sku: "MS10",
        purity: "99%+",
        content: "10mg",
        size: "10mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "MOTS-c",
        slug: "mots-c-40mg",
        description: "MOTS-C is a mitochondrial-derived peptide that influences metabolic regulation. Research shows benefits for energy, weight management, insulin sensitivity, and exercise performance.",
        price: 195,
        images: ["/images/peptide-injections.webp"],
        category: "Performance",
        stock: 100,
        sku: "MS40",
        purity: "99%+",
        content: "40mg",
        size: "40mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "SLU-PP-322",
        slug: "slu-pp-322",
        description: "SLU-PP-322 is a synthetic peptide that acts as a PPAR modulator. Research indicates benefits for metabolic health, glucose regulation, and fat metabolism.",
        price: 110,
        images: ["/images/peptide-injections.webp"],
        category: "Weight Loss",
        stock: 100,
        sku: "322",
        purity: "99%+",
        content: "10mg",
        size: "10mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Epithalon",
        slug: "epithalon-10mg",
        description: "Epithalon is a synthetic peptide that regulates telomere length and cellular aging. Research indicates anti-aging, antioxidant, and rejuvenating properties.",
        price: 55,
        images: ["/images/peptide-injections.webp"],
        category: "Recovery",
        stock: 100,
        sku: "ET10",
        purity: "99%+",
        content: "10mg",
        size: "10mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Epithalon",
        slug: "epithalon-50mg",
        description: "Epithalon is a synthetic peptide that regulates telomere length and cellular aging. Research indicates anti-aging, antioxidant, and rejuvenating properties.",
        price: 155,
        images: ["/images/peptide-injections.webp"],
        category: "Recovery",
        stock: 100,
        sku: "ET50",
        purity: "99%+",
        content: "50mg",
        size: "50mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "PT-141",
        slug: "pt-141-10mg",
        description: "PT-141 (Bremelanotide) is a synthetic peptide that acts on melanocortin receptors. Research shows benefits for sexual dysfunction and appetite suppression.",
        price: 70,
        images: ["/images/peptide-injections.webp"],
        category: "Performance",
        stock: 100,
        sku: "P41",
        purity: "99%+",
        content: "10mg",
        size: "10mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "DSIP",
        slug: "dsip-5mg",
        description: "DSIP (Delta-Sleep Inducing Peptide) promotes deep sleep and circadian rhythm regulation. Research shows potential for sleep disorders, stress management, and recovery.",
        price: 55,
        images: ["/images/peptide-injections.webp"],
        category: "Recovery",
        stock: 100,
        sku: "DS5",
        purity: "99%+",
        content: "5mg",
        size: "5mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "DSIP",
        slug: "dsip-10mg",
        description: "DSIP (Delta-Sleep Inducing Peptide) promotes deep sleep and circadian rhythm regulation. Research shows potential for sleep disorders, stress management, and recovery.",
        price: 85,
        images: ["/images/peptide-injections.webp"],
        category: "Recovery",
        stock: 100,
        sku: "DS10",
        purity: "99%+",
        content: "10mg",
        size: "10mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Dermorphin",
        slug: "dermorphin-5mg",
        description: "Dermorphin is a naturally occurring opioid peptide with potent analgesic properties. Research shows high affinity for mu-opioid receptors.",
        price: 45,
        images: ["/images/peptide-injections.webp"],
        category: "Recovery",
        stock: 100,
        sku: "DR5",
        purity: "99%+",
        content: "5mg",
        size: "5mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Thymosin Alpha-1",
        slug: "thymosin-alpha-1-5mg",
        description: "Thymosin Alpha-1 is an immune-modulating peptide that enhances T-cell function and immune response. Research shows benefits for immune deficiency and viral infections.",
        price: 95,
        images: ["/images/peptide-injections.webp"],
        category: "Recovery",
        stock: 100,
        sku: "TA5",
        purity: "99%+",
        content: "5mg",
        size: "5mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Thymosin Alpha-1",
        slug: "thymosin-alpha-1-10mg",
        description: "Thymosin Alpha-1 is an immune-modulating peptide that enhances T-cell function and immune response. Research shows benefits for immune deficiency and viral infections.",
        price: 165,
        images: ["/images/peptide-injections.webp"],
        category: "Recovery",
        stock: 100,
        sku: "TA10",
        purity: "99%+",
        content: "10mg",
        size: "10mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Sermorelin Acetate",
        slug: "sermorelin-acetate-5mg",
        description: "Sermorelin Acetate is a growth hormone-releasing hormone (GHRH) analog that stimulates pituitary gland to produce and secrete growth hormone. Used for growth hormone deficiency.",
        price: 90,
        images: ["/images/peptide-injections.webp"],
        category: "Performance",
        stock: 100,
        sku: "SMO5",
        purity: "99%+",
        content: "5mg",
        size: "5mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Sermorelin Acetate",
        slug: "sermorelin-acetate-10mg",
        description: "Sermorelin Acetate is a growth hormone-releasing hormone (GHRH) analog that stimulates pituitary gland to produce and secrete growth hormone. Used for growth hormone deficiency.",
        price: 115,
        images: ["/images/peptide-injections.webp"],
        category: "Performance",
        stock: 100,
        sku: "SMO10",
        purity: "99%+",
        content: "10mg",
        size: "10mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "HCG",
        slug: "hcg-5000iu",
        description: "Human Chorionic Gonadotropin (HCG) is a hormone that supports normal pregnancy and is used in research for fertility, testosterone stimulation, and weight loss protocols.",
        price: 90,
        images: ["/images/peptide-injections.webp"],
        category: "Performance",
        stock: 100,
        sku: "G5K",
        purity: "99%+",
        content: "5000IU",
        size: "5000IU*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "HCG",
        slug: "hcg-10000iu",
        description: "Human Chorionic Gonadotropin (HCG) is a hormone that supports normal pregnancy and is used in research for fertility, testosterone stimulation, and weight loss protocols.",
        price: 155,
        images: ["/images/peptide-injections.webp"],
        category: "Performance",
        stock: 100,
        sku: "G10K",
        purity: "99%+",
        content: "10000IU",
        size: "10000IU*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "GHRP-6 Acetate",
        slug: "ghrp-6-acetate-5mg",
        description: "GHRP-6 Acetate is a growth hormone-releasing peptide (GHRP) that stimulates GH release through ghrelin receptor activation. Promotes appetite and muscle growth.",
        price: 40,
        images: ["/images/peptide-injections.webp"],
        category: "Performance",
        stock: 100,
        sku: "G65",
        purity: "99%+",
        content: "5mg",
        size: "5mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "GHRP-6 Acetate",
        slug: "ghrp-6-acetate-10mg",
        description: "GHRP-6 Acetate is a growth hormone-releasing peptide (GHRP) that stimulates GH release through ghrelin receptor activation. Promotes appetite and muscle growth.",
        price: 60,
        images: ["/images/peptide-injections.webp"],
        category: "Performance",
        stock: 100,
        sku: "G610",
        purity: "99%+",
        content: "10mg",
        size: "10mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "IGF-DES",
        slug: "igf-des-2mg",
        description: "IGF-1 DES (1-3) is a truncated analog of IGF-1 with enhanced anabolic activity. Research shows benefits for muscle growth, tissue repair, and fat loss.",
        price: 70,
        images: ["/images/peptide-injections.webp"],
        category: "Performance",
        stock: 100,
        sku: "IGD",
        purity: "99%+",
        content: "2mg",
        size: "2mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "SS-31",
        slug: "ss-31-10mg",
        description: "SS-31 (Elamipretide) is a mitochondrial-targeted peptide that improves cellular energy production. Research shows benefits for cardiovascular health, aging, and exercise performance.",
        price: 100,
        images: ["/images/peptide-injections.webp"],
        category: "Recovery",
        stock: 100,
        sku: "2S10",
        purity: "99%+",
        content: "10mg",
        size: "10mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "SS-31",
        slug: "ss-31-50mg",
        description: "SS-31 (Elamipretide) is a mitochondrial-targeted peptide that improves cellular energy production. Research shows benefits for cardiovascular health, aging, and exercise performance.",
        price: 355,
        images: ["/images/peptide-injections.webp"],
        category: "Recovery",
        stock: 100,
        sku: "2S50",
        purity: "99%+",
        content: "50mg",
        size: "50mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "MT-1",
        slug: "mt-1-10mg",
        description: "MT-1 (Melanotan I) is a synthetic analog of alpha-melanocyte stimulating hormone (alpha-MSH). Promotes melanogenesis and tanning response for skin protection.",
        price: 55,
        images: ["/images/peptide-injections.webp"],
        category: "Performance",
        stock: 100,
        sku: "MT1",
        purity: "99%+",
        content: "10mg",
        size: "10mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Mazdutide",
        slug: "mazdutide-5mg",
        description: "Mazdutide is a dual glucagon and GLP-1 receptor agonist for metabolic regulation. Research shows benefits for obesity, diabetes, and cardiovascular health.",
        price: 120,
        images: ["/images/peptide-injections.webp"],
        category: "Weight Loss",
        stock: 100,
        sku: "MDT5",
        purity: "99%+",
        content: "5mg",
        size: "5mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Mazdutide",
        slug: "mazdutide-10mg",
        description: "Mazdutide is a dual glucagon and GLP-1 receptor agonist for metabolic regulation. Research shows benefits for obesity, diabetes, and cardiovascular health.",
        price: 210,
        images: ["/images/peptide-injections.webp"],
        category: "Weight Loss",
        stock: 100,
        sku: "MDT10",
        purity: "99%+",
        content: "10mg",
        size: "10mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "BPC Blend (GLOW)",
        slug: "bpc-blend-glow",
        description: "BPC Blend containing BPC-157 (10mg), GHK-Cu (50mg), and TB-500 (10mg). A comprehensive blend for tissue repair, wound healing, and anti-inflammatory benefits.",
        price: 190,
        images: ["/images/peptide-injections.webp"],
        category: "Recovery",
        stock: 100,
        sku: "GLOW(BBG70)",
        purity: "99%+",
        content: "70mg",
        size: "70mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "KLOW Blend",
        slug: "klow-blend",
        description: "KLOW Blend containing GHK-Cu (50mg), TB-500 (10mg), BPC-157 (10mg), and KPV (10mg). A comprehensive blend for skin health, tissue repair, and anti-inflammatory benefits.",
        price: 225,
        images: ["/images/peptide-injections.webp"],
        category: "Recovery",
        stock: 100,
        sku: "KLOW",
        purity: "99%+",
        content: "80mg",
        size: "80mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Cagrilintide + Semaglutide Blend",
        slug: "cagrilintide-semaglutide-5mg",
        description: "Blend of Cagrilintide (2.5mg) and Semaglutide (2.5mg). Dual mechanism for enhanced weight loss through amylin receptor agonism and GLP-1 pathway.",
        price: 135,
        images: ["/images/peptide-injections.webp"],
        category: "Weight Loss",
        stock: 100,
        sku: "CS5",
        purity: "99%+",
        content: "5mg",
        size: "5mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "Cagrilintide + Semaglutide Blend",
        slug: "cagrilintide-semaglutide-10mg",
        description: "Blend of Cagrilintide (5mg) and Semaglutide (5mg). Dual mechanism for enhanced weight loss through amylin receptor agonism and GLP-1 pathway.",
        price: 210,
        images: ["/images/peptide-injections.webp"],
        category: "Weight Loss",
        stock: 100,
        sku: "CS10",
        purity: "99%+",
        content: "10mg",
        size: "10mg*10vials",
        form: "Lyophilized Powder",
    },
    {
        name: "LC120",
        slug: "lc120",
        description: "LC120 is a liquid peptide formulation for research purposes. Designed for enhanced stability and bioavailability.",
        price: 70,
        images: ["/images/peptide-injections.webp"],
        category: "Performance",
        stock: 100,
        sku: "LC120",
        purity: "99%+",
        content: "10ml",
        size: "10ml*10vials",
        form: "Liquid Solution",
    },
    {
        name: "LC216",
        slug: "lc216",
        description: "LC216 is a liquid peptide formulation with B12 included for enhanced energy and metabolism support. Designed for research purposes with improved bioavailability.",
        price: 70,
        images: ["/images/peptide-injections.webp"],
        category: "Performance",
        stock: 100,
        sku: "LC216",
        purity: "99%+",
        content: "10ml",
        size: "10ml*10vials",
        form: "Liquid Solution",
    },
    {
        name: "Bacteriostatic Water",
        slug: "bacteriostatic-water-3ml",
        description: "Bacteriostatic Water (BAC Water) for injection preparation. Sterile water with 0.9% benzyl alcohol for peptide reconstitution.",
        price: 8,
        images: ["/images/peptide-injections.webp"],
        category: "Accessories",
        stock: 500,
        sku: "WA3",
        purity: "N/A",
        content: "3mL",
        size: "3mL*10vials",
        form: "Liquid",
    },
    {
        name: "Bacteriostatic Water",
        slug: "bacteriostatic-water-10ml",
        description: "Bacteriostatic Water (BAC Water) for injection preparation. Sterile water with 0.9% benzyl alcohol for peptide reconstitution.",
        price: 12,
        images: ["/images/peptide-injections.webp"],
        category: "Accessories",
        stock: 500,
        sku: "WA10",
        purity: "N/A",
        content: "10mL",
        size: "10mL*10vials",
        form: "Liquid",
    },
];

async function seedProducts() {
    try {
        const mongoUri = process.env.MONGODB_URI;
        if (!mongoUri) {
            console.error('MONGODB_URI not found in .env.local');
            process.exit(1);
        }
        
        await mongoose.connect(mongoUri);
        console.log('Connected to MongoDB');

        let inserted = 0;
        let updated = 0;

        for (const product of products) {
            const result = await Product.findOneAndUpdate(
                { sku: product.sku },
                { $set: product },
                { upsert: true, new: true, setDefaultsOnInsert: true }
            );
            if (result) {
                updated++;
            }
        }

        console.log(`\n✓ Processed ${products.length} products`);
        console.log(`  Total products in database: ${await Product.countDocuments()}`);
        
    } catch (error) {
        console.error('Error seeding products:', error);
    } finally {
        await mongoose.disconnect();
        console.log('Disconnected from MongoDB');
    }
}

seedProducts();
